language: php

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/grumphp run

notifications:
  email:
    on_success: never
